### ISSUE TITLE
windows command fails to mount network drive because a trailing backslash is always included in drivePath

### ISSUE THREAD

**Issue by jayemdee** [larrybahr/windows-network-drive#1]
If you drop this trailing backslash the command (net use) completes successfully.  

Let me know if you need more details...

**Comment by larrybahr** [comment]
Thank you for submitting an issue for this. All my tests succeeded with or without the trailing backslash until I tested `\\localhost\c$`. I updated the code with your suggestion and added you to the contributors section of the package.json.

**Comment by jayemdee** [comment]
Very nice! thank you for the extremely fast response!  I made essentially the same fix but so much nicer to just be able to pull in the new release with npm.  Tested and works fine.
