### ISSUE TITLE
Bug: list() doesn't return all network drives

### ISSUE THREAD

**Issue by nytamin** [larrybahr/windows-network-drive#24]
On my system (Windows 10), the `list()` command currently returns

```
await list() //  { "Z":  "\\\\my\\network\\path" }
```
but I have more devices than that.

If I run `wmic path Win32_LogicalDisk Where DriveType=\"4\" get DeviceID, ProviderName` I get
```
DeviceID  ProviderName                  
Z:        \\my\network\path
```
but if I run `net use` without any more arguments, I get:
```
New connections will be remembered.
Status       Local     Remote                    Network
-------------------------------------------------------------------------------
OK           Z:        \\my\network\path Microsoft Windows Network
Not avail U:        \\my\network\path2 Microsoft Windows Network
Not avail V:        \\my\network\path3 Microsoft Windows Network
The command completed successfully.
```

If I look in "This computer" I have indeed Z, U and V mapped up, although U & V have issues due to the current network conditions.

To explain why this is an issue, I'll give an example:
``` javascript
// My application

const WND = require('windows-network-drive')
const drivesToMapUp = {
  Z: "\\my\network\path",
  U: "\\my\network\path2"
}

// Get a list of existing drives:
const existing = await WND.list() // Returns { "Z":  "\\\\my\\network\\path" }

// Go through my drives and map up
for (const o of Object.entries(drivesToMapUp)) {
  const key = o[0]
  const value = o[1]

  if (!existing[key]) {
    await WND.mount(value, key) // This throws an error
  } else if (existing[key] !== value) {
    await WND.unmount(key)
    await WND.mount(value, key)
  }

}
```

The code abode throws an error, because it'll try to mount `U`, but since it is already taken I get an error message.

I have a potential fix ready for this, by replacing the call to `wmic` with a `net use` command. Before I submit that Pull Request, I'd like to raise the question whether there was any particular reason to go for `wmic` instead of `net use` in the first place?

**Comment by larrybahr** [comment]
The reason was that I only wanted the usable drives, but I see your point here. 

PR is welcome. The only thing I would suggest is that it return if the drive is usable or if it is offline
