### ISSUE TITLE
net use /P:Yes optional

### ISSUE THREAD

**Issue by TomFuch** [larrybahr/windows-network-drive#28]
It would be great if the P-Flag ( net use ... ) is an Option in mount function.

**Comment by larrybahr** [comment]
What is the use case where this would be needed?

That seems like a great first PR for the project! I would start with adding an options param in [mount](https://github.com/larrybahr/windows-network-drive/blob/master/index.js#L240), and then change the command based on flags [here](https://github.com/larrybahr/windows-network-drive/blob/master/index.js#L331).
PR is welcome

**Comment by larrybahr** [comment]
Closing for now, but if you have any more questions feel free to comment.

**Comment by TomFuch** [comment]
> What is the use case where this would be needed?
> 
> That seems like a great first PR for the project! I would start with adding an options param in [mount](https://github.com/larrybahr/windows-network-drive/blob/master/index.js#L240), and then change the command based on flags [here](https://github.com/larrybahr/windows-network-drive/blob/master/index.js#L331). PR is welcome

I need this for a backup script that mount a network drive to a NAS, but after restart this share should not be automatically connected...
