### ISSUE TITLE
How can I access Network drive on Windows while nodejs is on CentOS

### ISSUE THREAD

**Issue by rajkaran** [larrybahr/windows-network-drive#4]
I tried installing this package but console threw this error

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for windows-drive-letters@3.1.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

```
Seems like this package is not for linux systems..

**Comment by larrybahr** [comment]
That is correct. This package is only for managing network drives on Microsoft Windows. 
I know the readme states that Windows is supported. Did you see anywhere that I mistakenly added Linux as a supported system?

**Comment by rajkaran** [comment]
Thank you for quick reply 

`Allows a user to do network drive stuff on Microsoft Windows from node js`
`Convert Unix paths to Windows friendly paths`

these two statements made me think it can handle... node can run on any system...

**Comment by larrybahr** [comment]
I understand where the confusion came in. I added that functionality because I had a large number of Linux style paths I needed to mount on a Windows computer. At some point I do plan to support generic methods like that on Linux, but I do not know when I will have the time to make the change.
