### ISSUE TITLE
Error Throw from WMIC

### ISSUE THREAD

**Issue by cenk1cenk2** [larrybahr/windows-network-drive#5]
I get a error from [index.js:143](https://github.com/larrybahr/windows-network-drive/blob/4193b029db2ad49c16ad5d53f1bbfb3c2217f024/index.js#L153) while trying to list or mount the shares. WMIC throws out "No Instance(s) Available." and not sure what is wrong, so the script can not proceed.

**Comment by larrybahr** [comment]
What version of Windows are you using?

**Comment by cenk1cenk2** [comment]
I am using v1809 17763.503.

**Comment by larrybahr** [comment]
I pushed a fix to the github repo (version 2.1.2).
Can you verify it fixes your issue?

**Comment by cenk1cenk2** [comment]
It will fix the issue looking at the commit. Thank you.

**Comment by eirikkva** [comment]
I have the same issue, will the 2.1.2 version be published to npm as well? That would be great :)

**Comment by larrybahr** [comment]
Yes, I am working with the NPM team to fix an issue with 2FA. Somehow my account does not have 2FA enabled, but the package still requires 2FA. I expect to have it updated some time today or early tomorrow at the latest.
